name: Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report

      - name: Upload traces and screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts
          path: |
            test-results
            allure-results
